<!DOCTYPE html>
<html>

  <head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>1 Vector Mathematics with unset</title>
  <meta name="description" content="This guide discusses vector math including vector representation, vector operation, and line and plane equations.  Using unset">

  <!-- OpenGraph for Facebook, Twitter, Slack unfurling -->
  <meta property="og:type" content="website" />
  <meta property="og:url" content="/guides/general/essential-mathematics/vector-mathematics/" />
  <meta property="og:title" content="1 Vector Mathematics" />
  <meta property="og:description" content="This guide discusses vector math including vector representation, vector operation, and line and plane equations." />
  <meta property=”og:site_name” content="developer.rhino3d.com"/>
  <meta property=”og:image” content="http://developer.rhino3d.com/images/rhinodev-logo-unfurl.png"/>

  <!-- twitter card tags additive with the og: tags -->
  <meta name="twitter:domain" value="developer.rhino3d.com" />
  <meta name="twitter:title" value="1 Vector Mathematics" />
  <meta name="twitter:description" value="This guide discusses vector math including vector representation, vector operation, and line and plane equations." />
  
    <meta name="twitter:image" content="http://developer.rhino3d.com/images/rhinodev-logo-unfurl.png" />
  
  <meta name="twitter:url" value="http://developer.rhino3d.com" />
  
  <meta name="twitter:label1" value="Platform(s)" />
  <meta name="twitter:data1" value="Windows, Mac" />
  
  
  <meta name="twitter:label2" value="Language(s)" />
  <meta name="twitter:data2" value="unset" />
  

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/github.min.css">
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/vbnet.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/yaml.min.js"></script>
  <script src="/node_modules/highlightjs-line-numbers.js/dist/highlightjs-line-numbers.min.js"></script>
  <script>hljs.initHighlightingOnLoad();</script>
  <script>hljs.initLineNumbersOnLoad();</script>

  <!-- Overridden theme -->
  <link rel="stylesheet" href="/css/main.css">

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <!-- Optional theme -->
  <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous"> -->
  <!-- Bootstrap override -->
  <link rel="stylesheet" href="/css/bootstrap-override.css">

  <link rel="canonical" href="http://developer.rhino3d.com/guides/general/essential-mathematics/vector-mathematics/">
  <link rel="alternate" type="application/rss+xml" title="Rhino Developer Docs" href="http://developer.rhino3d.com/feed.xml" />

  <link rel="shortcut icon" href="https://developer.rhino3d.com/favicon.ico?v=2" />
  <!-- Saving bookmarks to mobile devices -->
  <!-- For non-Retina (@1× display) iPhone, iPod Touch, and Android 2.1+ devices: -->
  <link rel="apple-touch-icon-precomposed" href="/images/apple-touch-icon-precomposed.png"><!-- 57×57px -->
  <!-- For the iPad mini and the first- and second-generation iPad (@1× display) on iOS ≤ 6: -->
  <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/images/apple-touch-icon-72x72-precomposed.png">
  <!-- For the iPad mini and the first- and second-generation iPad (@1× display) on iOS ≥ 7: -->
  <link rel="apple-touch-icon-precomposed" sizes="76x76" href="/images/apple-touch-icon-76x76-precomposed.png">
  <!-- For iPhone with @2× display running iOS ≤ 6: -->
  <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/images/apple-touch-icon-114x114-precomposed.png">
  <!-- For iPhone with @2× display running iOS ≥ 7: -->
  <link rel="apple-touch-icon-precomposed" sizes="120x120" href="/images/apple-touch-icon-120x120-precomposed.png">
  <!-- For iPad with @2× display running iOS ≤ 6: -->
  <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/images/apple-touch-icon-144x144-precomposed.png">
  <!-- For iPad with @2× display running iOS ≥ 7: -->
  <link rel="apple-touch-icon-precomposed" sizes="152x152" href="/images/apple-touch-icon-152x152-precomposed.png">
  <!-- For iPhone 6 Plus with @3× display: -->
  <link rel="apple-touch-icon-precomposed" sizes="180x180" href="/images/apple-touch-icon-180x180-precomposed.png">
  <!-- For Chrome for Android: -->
  <link rel="icon" sizes="192x192" href="/images/touch-icon-192x192.png">

  <!-- Enable crawling because this version is the stable version -->
  <!--<meta name="robots" content="noindex" />-->
</head>


  <body>

    <!-- Google Tag Manager **This belongs right after the <body> tag**-->
    <noscript>
        <iframe src="//www.googletagmanager.com/ns.html?id=GTM-MWMDKN"
        height="0" width="0" style="display:none;visibility:hidden"></iframe>
    </noscript>
    <script>
        (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
        new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
        j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
        '//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
        })(window,document,'script','dataLayer','GTM-MWMDKN');
    </script>
    <!-- End Google Tag Manager -->


    

<!-- The following are "casts" from the string to number using math filters... -->



<!-- ...but we need to check to see if the original branches were numbers or not... -->









  <div class="version-banner">

    
      
        
        
          <!-- <strong>NEW:</strong> Welcome to the <strong>Rhino 7</strong> version of this page! <a href="/6/guides/general/essential-mathematics/vector-mathematics/">Looking for the older Rhino 6 version?</a> -->
          Welcome to the <strong>Rhino 7</strong> version of this page!
          <a href="/wip/guides/general/essential-mathematics/vector-mathematics/">Looking for the newer Rhino 8 WIP version?</a>
        
        
      
    
</div>

<!-- Check the version banner for broken links and remove the link if found -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<!-- <script>
$(document).ready(function()
{
  var splitPath = window.location.pathname.split("/");
  var linkURL = "/" + splitPath.splice(2,splitPath.length-2).join("/");

  $.get(linkURL).fail(function ()
  {
    var $aTag = $("div.version-banner > a");
    $aTag.text("View the current site instead.");
    $aTag.attr("href", "/");
  });
});
</script> -->


    <div class="container">

      <header class="site-header">


    <a class="site-title" href="/"><img src="/images/rhinodevlogo148x128.png" alt="Rhino Developer Docs" height="48" width="56"></a><a class="site-title" href="/">Rhino Developer Docs</a>

    <nav class="site-nav">
      <img class="menu-icon" src="/images/gi.svg">
      
      <div class="trigger">
      	<!--<a class="page-link" href="/">Welcome</a>-->
        <!-- get current page title and "collection" to figure out which nav
             link should be "active" -->
        
        
        
        
          
            
              
                
              
            
          
        
          
            
              
                
              
            
          
        
          
            
              
                
              
            
          
        
          
            
              
                
              
            
          
        
          
            
              
                
              
            
          
        
          
            
              
                
              
            
          
        
          
            
              
                
              
            
          
        
          
            
              
                
              
            
          
        
          
            
              
                
              
            
          
        
          
            
              
                
              
            
          
        
          
            
              
                
              
            
          
        
          
            
              
                
              
            
          
        
          
            
              
                
              
            
          
        
          
            
              
                
              
            
          
        
          
            
              
                
              
            
          
        
          
            
              
                
              
            
          
        
          
            
              
                
              
            
          
        
          
            
              
                
              
            
          
        
          
        
          
            
              
            
          
        
          
            
              
                
                  
                    <a class="page-link active" href="/guides/">Guides</a>
                    
                  
              
            
          
        
          
            
              
                
                  
                    <a class="page-link" href="/api/">API</a>
                    
                  
              
            
          
        
          
            
              
                
                  
                    <a class="page-link" href="/samples/">Samples</a>
                    
                  
              
            
          
        
          
            
          
        
          
            
              
                
                  
                    <a class="page-link" href="/videos/">Videos</a>
                    
                  
              
            
          
        
        <a class="page-link" href="https://discourse.mcneel.com/c/rhino-developer">Forums</a>
        <!-- Google Search Engine -->
        <!-- TODO Move to this site back into the Mcneel search, or use a simple site only search for results -->
        <div id="sitesearch">
            <!-- CSE Search Box Begins  -->
            <form id="search-box" name="search-box" onsubmit="sitesearchFunction()" action="/search-results.html">
                <input id="searchtext" type="search" name="q" size="24" value="" placeholder="Search" />
                <input class="searchBox" type="submit" size="2" value=" " />
            </form>
			<script type="text/javascript">
			function sitesearchFunction(){
				var form_id = document.getElementById("search-box");
				var form_action = form_id.action;
                var form_sb = document.getElementById("searchtext");
				var query_src = form_sb.value + " site:developer.rhino3d.com";
				form_sb.value = query_src.toString();
			}
			</script>
<!-- Google CSE Search Box Ends -->
        </div>
        <!--End of Google Search Engine -->
      </div>
    </nav>

</header>


      <div class="page-content">
        <!--div class="wrapper"-->
          <div class="container-fluid">

<div class="row-fluid">
    <!--Nav Bar -->
    <nav class="col-xs-0 col-md-3 bs-docs-sidebar">
    <ul id="sidebar" class="nav nav-stacked fixed">
        <!-- Find the h2 group and any h3 subgroups -->
        

        
          

          
            
            
            
            
            <li>
              <a href="#11-vector-representation">1.1 Vector representation</a>

              
                <ul class="nav nav-stacked">
                  

                  
                    
                    
                    
                    
                    
                    <li>
                        <a href="#position-vector">Position vector</a>
                    </li>
                  
                    
                    
                    
                    
                    
                    <li>
                        <a href="#vectors-vs-points">Vectors vs. points</a>
                    </li>
                  
                    
                    
                    
                    
                    
                    <li>
                        <a href="#vector-length">Vector length</a>
                    </li>
                  
                    
                    
                    
                    
                    
                    <li>
                        <a href="#unit-vector">Unit vector</a>
                    </li>
                  

                </ul>
              

            </li>
          

        
          

          
            
            
            
            
            <li>
              <a href="#12-vector-operations">1.2 Vector operations</a>

              
                <ul class="nav nav-stacked">
                  

                  
                    
                    
                    
                    
                    
                    <li>
                        <a href="#vector-scalar-operation">Vector scalar operation</a>
                    </li>
                  
                    
                    
                    
                    
                    
                    <li>
                        <a href="#vector-addition">Vector addition</a>
                    </li>
                  
                    
                    
                    
                    
                    
                    <li>
                        <a href="#vector-subtraction">Vector subtraction</a>
                    </li>
                  
                    
                    
                    
                    
                    
                    <li>
                        <a href="#vector-properties">Vector properties</a>
                    </li>
                  
                    
                    
                    
                    
                    
                    <li>
                        <a href="#vector-dot-product">Vector dot product</a>
                    </li>
                  
                    
                    
                    
                    
                    
                    <li>
                        <a href="#vector-dot-product-lengths-and-angles">Vector dot product, lengt...</a>
                    </li>
                  
                    
                    
                    
                    
                    
                    <li>
                        <a href="#dot-product-properties">Dot product properties</a>
                    </li>
                  
                    
                    
                    
                    
                    
                    <li>
                        <a href="#vector-cross-product">Vector cross product</a>
                    </li>
                  
                    
                    
                    
                    
                    
                    <li>
                        <a href="#cross-product-and-angle-between-vectors">Cross product and angle b...</a>
                    </li>
                  
                    
                    
                    
                    
                    
                    <li>
                        <a href="#cross-product-properties">Cross product properties</a>
                    </li>
                  

                </ul>
              

            </li>
          

        
          

          
            
            
            
            
            <li>
              <a href="#13-vector-equation-of-line">1.3 Vector equation of line</a>

              

            </li>
          

        
          

          
            
            
            
            
            <li>
              <a href="#14-vector-equation-of-a-plane">1.4 Vector equation of a ...</a>

              

            </li>
          

        
          

          
            
            
            
            
            <li>
              <a href="#15-tutorials">1.5 Tutorials</a>

              
                <ul class="nav nav-stacked">
                  

                  
                    
                    
                    
                    
                    
                    <li>
                        <a href="#151-face-direction">1.5.1 Face direction</a>
                    </li>
                  
                    
                    
                    
                    
                    
                    <li>
                        <a href="#152-exploded-box">1.5.2 Exploded box</a>
                    </li>
                  
                    
                    
                    
                    
                    
                    <li>
                        <a href="#153-tangent-spheres">1.5.3 Tangent spheres</a>
                    </li>
                  

                </ul>
              

            </li>
          

        
          

          
            
            
            
            
            <li>
              <a href="#download-sample-files">Download Sample Files</a>

              

            </li>
          

        
          

          
            
            
            
            
            <li>
              <a href="#next-steps">Next Steps</a>

              

            </li>
          

        
    </ul>
</nav>


    <!--Main Content -->
    <div class="col-xs-12 col-md-9">
      <!--<div class="post">-->

        <article class="post-content">

          <ol class="breadcrumb">
              
              
              
              
              <li><a href="/guides/general">General</a></li>

              
                <li class="active"><a href="/guides/general/essential-mathematics/">Essential Mathematics</a></li>
              
          </ol>

          <h1>1 Vector Mathematics</h1>

          <p>
  <span class="guide_byline">
    
      
      by <a href="/authors/rajaa_issa">Rajaa Issa</a> (Last modified: <a href="https://github.com/mcneel/developer-rhino3d-com/commits/7/_guide_topics/general/essential-mathematics/vector-mathematics.md" target="_blank">07 Jun 2021</a>)
    
  </span>

</p>

          <p>This guide discusses vector math including vector representation, vector operation, and line and plane equations.</p>

          <p>A vector indicates a quantity, such as velocity or force, that has direction and length. Vectors in 3D coordinate systems are represented with an ordered set of three real numbers and look like:</p>

<p>\(\mathbf{\vec v}  = &lt;a_1, a_2, a_3&gt;\)</p>

<div class="embed-responsive embed-responsive-16by9 video-player">
  <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/NU34_aCoN3E?showinfo=0&amp;rel=0&amp;modestbranding=1" frameborder="0" allow="accelerometer; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe>
</div>

<p><br /></p>

<h2 id="11-vector-representation">1.1 Vector representation</h2>

<p>In this document, lower case bold letters with arrow on top will notate vectors. Vector components are also enclosed in angle brackets. Upper case letters will notate points. Point coordinates will always be enclosed by parentheses.</p>

<p>Using a coordinate system and any set of anchor points in that system, we can represent or visualize these vectors using a line-segment representation. An arrowhead shows the vector direction.</p>

<p>For example, if we have a vector that has a direction parallel to the x-axis of a given 3D coordinate system and a length of 5 units, we can write the vector as follows:</p>

<p>\(\mathbf{\vec v} = &lt;5, 0, 0&gt;\)</p>

<p>To represent that vector, we need an anchor point in the coordinate system. For example, all of the arrows in the following figure are equal representations of the same vector despite the fact that they are anchored at different locations.</p>

<figure>
   <img src="/images/math-image169.png" />
   <figcaption>Figure (1): Vector representation in the 3-D coordinate system.</figcaption>
</figure>

<div class="note">
  <p>Given a 3D vector \(\vec v = &lt;a_1, a_2, a_3&gt;\) , all vector components \(a_1\), \(a_2\), \(a_3\) are real numbers. Also all line segments from a point \(A(x,y,z)\) to point \(B(x+a_1, y+a_2, z+a_3)\) are equivalent representations of vector \(\vec v\).</p>
</div>

<p>So, how do we define the end points of a line segment that represents a given vector?
Let us define an anchor point (A) so that:</p>

<p>\(A = (1, 2, 3)\)</p>

<p>And a vector:</p>

<p>\(\mathbf{\vec v} = &lt;5, 6, 7&gt;\)</p>

<p>The tip point \((B)\) of the vector is calculated by adding the corresponding components from anchor point and vector \(\vec v\):</p>

<p>\(B = A + \mathbf{\vec v}\)<br />
\(B = (1+5, 2+6, 3+7)\)<br />
\(B = (6, 8, 10)\)</p>

<figure>
   <img src="/images/math-image172.png" />
   <figcaption>Figure (2): The relationship between a vector, the vector anchor point, and the point coinciding with the vector tip location.</figcaption>
</figure>

<div class="embed-responsive embed-responsive-16by9 video-player">
  <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/ELQ8NgENhJY?showinfo=0&amp;rel=0&amp;modestbranding=1" frameborder="0" allow="accelerometer; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe>
</div>

<p><br /></p>

<div class="embed-responsive embed-responsive-16by9 video-player">
  <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/INtNgczxyWg?showinfo=0&amp;rel=0&amp;modestbranding=1" frameborder="0" allow="accelerometer; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe>
</div>

<p><br /></p>

<h3 id="position-vector">Position vector</h3>

<p>One special vector representation uses the \(\text{origin point} (0,0,0)\) as the vector anchor point.
The position vector \(\mathbf{\vec v} = &lt;a_1,a_2,a_3&gt;\) is represented with a line segment between two points, the origin and the tip point B, so that:</p>

<p>\(\text{Origin point} = (0,0,0)\)<br />
\(B = (a_1,a_2,a_3)\)</p>

<figure>
   <img src="/images/math-image169.png" />
   <figcaption>Figure (1): Vector representation in the 3-D coordinate system.</figcaption>
</figure>

<div class="note">
  <p>A <em>position vector</em> for a given vector \(\vec v= &lt; a_1,a_2,a_3 &gt;\) is a special line segment representation from the origin point \((0,0,0)\) to point \((a_1, a_2, a_3)\).</p>
</div>

<div class="embed-responsive embed-responsive-16by9 video-player">
  <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/8BNyMC4EBcw?showinfo=0&amp;rel=0&amp;modestbranding=1" frameborder="0" allow="accelerometer; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe>
</div>

<p><br /></p>

<div class="embed-responsive embed-responsive-16by9 video-player">
  <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/Ft2edI4g1qY?showinfo=0&amp;rel=0&amp;modestbranding=1" frameborder="0" allow="accelerometer; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe>
</div>

<p><br /></p>

<h3 id="vectors-vs-points">Vectors vs. points</h3>

<p>Do not confuse vectors and points. They are very different concepts. Vectors, as we mentioned, represent a quantity that has direction and length, while points indicate a location. For example, the North direction is a vector, while the North Pole is a location (point).
If we have a vector and a point that have the same components, such as:</p>

<p>\(\mathbf{\vec v} = &lt;3,1,0&gt;\)<br />
\(P = (3,1,0)\)</p>

<p>We can draw the vector and the point as follows:</p>

<figure>
   <img src="/images/math-image174.png" />
   <figcaption>Figure (4): A vector defines a direction and length. A point defines a location.</figcaption>
</figure>

<div class="embed-responsive embed-responsive-16by9 video-player">
  <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/RRrTz_QO_rA?showinfo=0&amp;rel=0&amp;modestbranding=1" frameborder="0" allow="accelerometer; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe>
</div>

<p><br /></p>

<h3 id="vector-length">Vector length</h3>

<p>As mentioned before, vectors have length. We will use \(\vert a \vert\) to notate the length of a given vector \(a\). For example:</p>

<p>\(\mathbf{\vec a} = &lt;4, 3, 0&gt;\)<br />
\(\vert \mathbf{\vec a} \vert = \sqrt{4^2 + 3^2 + 0^2}\)<br />
\(\vert \mathbf{\vec a} \vert = 5\)</p>

<p>In general, the length of a vector \(\mathbf{\vec a} &lt;a_1,a_2,a_3&gt;\) is calculated as follows:</p>

<p>\(\vert \mathbf{\vec a} \vert = \sqrt{(a_1)^2 + (a_2)^2 + (a_3)^2}\)</p>

<figure>
   <img src="/images/math-image173.png" />
   <figcaption>Figure (5): Vector length.</figcaption>
</figure>

<h3 id="unit-vector">Unit vector</h3>

<p>A unit vector is a vector with a length equal to one unit. Unit vectors are commonly used to compare the directions of vectors.</p>

<div class="note">
  <p>A unit vector is a vector whose length is equal to one unit.</p>
</div>

<p>To calculate a unit vector, we need to find the length of the given vector, and then divide the vector components by the length. For example:</p>

<p>\(\mathbf{\vec a} = &lt;4, 3, 0&gt;\)<br />
       \(\vert \mathbf{\vec a} \vert = \sqrt{4^2 + 3^2 + 0^2}\)<br />
       \(\vert \mathbf{\vec a} \vert  = 5 \text{ unit length}\)</p>

<p>If \(\mathbf{\vec b} = \text{unit vector}\) of \(a\), then:<br />
       \(\mathbf{\vec b} = &lt;4/5, 3/5, 0/5&gt;\)<br />
       \(\mathbf{\vec b} = &lt;0.8, 0.6, 0&gt;\)<br />
       \(\vert \mathbf{\vec b} \vert  = \sqrt{0.8^2 + 0.6^2 + 0^2}\)<br />
       \(\vert \mathbf{\vec b} \vert  = \sqrt{0.64 + 0.36 + 0}\)<br />
       \(\vert \mathbf{\vec b} \vert  = \sqrt{(1)} = 1 \text{ unit length}\)</p>

<p>In general:</p>

<p>\(\mathbf{\vec a} = &lt;a_1, a_2, a_3&gt;\)</p>

<p>The unit vector of \(\mathbf{\vec a} = &lt;a_1/\vert \mathbf{\vec a} \vert , a_2/\vert \mathbf{\vec a} \vert , a_3/\vert \mathbf{\vec a} \vert &gt;\)</p>

<figure>
   <img src="/images/math-image176.png" />
   <figcaption>Figure (6): Unit vector equals one-unit length of the vector.</figcaption>
</figure>

<div class="embed-responsive embed-responsive-16by9 video-player">
  <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/yVSigpl3EUo?showinfo=0&amp;rel=0&amp;modestbranding=1" frameborder="0" allow="accelerometer; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe>
</div>

<p><br /></p>

<h2 id="12-vector-operations">1.2 Vector operations</h2>

<div class="embed-responsive embed-responsive-16by9 video-player">
  <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/uInxocphhxI?showinfo=0&amp;rel=0&amp;modestbranding=1" frameborder="0" allow="accelerometer; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe>
</div>

<p><br /></p>

<h3 id="vector-scalar-operation">Vector scalar operation</h3>

<p>Vector scalar operation involves multiplying a vector by a number. For example:</p>

<p>\(\mathbf{\vec a} = &lt;4, 3, 0&gt;\)<br />
\(2* \mathbf{\vec a} = &lt;2*4, 2*3, 2*0&gt;\)<br />
\(2*\mathbf{\vec a} = &lt;8, 6, 0&gt;\)</p>

<figure>
   <img src="/images/math-image175.png" />
   <figcaption>Figure (7): Vector scalar operation</figcaption>
</figure>

<p>In general, given vector \(\mathbf{\vec a} = &lt;a_1, a_2, a_3&gt;\), and a real number \(t\)</p>

<p>\(t*\mathbf{\vec a} = &lt; t* a_1, t* a_2, t* a_3 &gt;\)</p>

<div class="embed-responsive embed-responsive-16by9 video-player">
  <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/S59M8BnDYAQ?showinfo=0&amp;rel=0&amp;modestbranding=1" frameborder="0" allow="accelerometer; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe>
</div>

<p><br /></p>

<h3 id="vector-addition">Vector addition</h3>

<p>Vector addition takes two vectors and produces a third vector. We add vectors by adding their components.</p>

<div class="note">
  <p>Vectors are added by adding their components.</p>
</div>

<p>For example, if we have two vectors:</p>

<p>\(\mathbf{\vec a} = &lt;1, 2, 0&gt;\)<br />
\(\mathbf{\vec b} = &lt;4, 1, 3&gt;\) <br />
\(\mathbf{\vec a}+\mathbf{\vec b} = &lt;1+4, 2+1, 0+3&gt;\)<br />
\(\mathbf{\vec a}+\mathbf{\vec b} = &lt;5, 3, 3&gt;\)</p>

<figure>
   <img src="/images/math-image179.png" />
   <figcaption>Figure (8): Vector addition.</figcaption>
</figure>

<p>In general, vector addition of the two vectors a and b is calculated as follows:</p>

<p>\(\mathbf{\vec a} = &lt;a_1, a_2, a_3&gt;\)<br />
\(\mathbf{\vec b} = &lt;b_1, b_2, b_3&gt;\)<br />
\(\mathbf{\vec a}+\mathbf{\vec b} = &lt;a_1+b_1, a_2+b_2, a_3+b_3&gt;\)</p>

<p>Vector addition is useful for finding the average direction of two or more vectors. In this case, we usually use same-length vectors. Here is an example that shows the difference between using same-length vectors and different-length vectors on the resulting vector addition:</p>

<figure>
   <img src="/images/math-image177.png" />
   <figcaption>Figure (9): Adding various length vectors (left). Adding same length vectors (right) to get the average direction.</figcaption>
</figure>

<p>Input vectors are not likely to be same length. In order to find the average direction, you need to use the unit vector of input vectors. As mentioned before, the unit vector is a vector of that has a length equal to 1.</p>

<div class="embed-responsive embed-responsive-16by9 video-player">
  <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/VTVk3t3WeAY?showinfo=0&amp;rel=0&amp;modestbranding=1" frameborder="0" allow="accelerometer; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe>
</div>

<p><br /></p>

<h3 id="vector-subtraction">Vector subtraction</h3>

<p>Vector subtraction takes two vectors and produces a third vector. We subtract two vectors by subtracting corresponding components. For example, if we have two vectors \(\mathbf{\vec a}\) and \(\mathbf{\vec b}\) and we subtract \(\mathbf{\vec b}\) from \(\mathbf{\vec a}\), then:</p>

<p>\(\mathbf{\vec a} = &lt;1, 2, 0&gt;\)<br />
\(\mathbf{\vec b} = &lt;4, 1, 4&gt;\)<br />
\(\mathbf{\vec a}-\mathbf{\vec b} = &lt;1-4, 2-1, 0-4&gt;\)<br />
\(\mathbf{\vec a}-\mathbf{\vec b} = &lt;-3, 1, -4&gt; = \mathbf{\mathbf{\vec b}a}\)</p>

<p>If we subtract \(\mathbf{\vec b}\) from \(\mathbf{\vec a}\), we get a different result:</p>

<p>\(\mathbf{\vec b} - \mathbf{\vec a} = &lt;4-1, 1-2, 4-0&gt;\)<br />
\(\mathbf{\vec b} - \mathbf{\vec a} = &lt;3, -1, 4&gt; = \mathbf{\mathbf{\vec a}b}\)</p>

<p>Note that the vector \(\mathbf{\vec b} - \mathbf{\vec a}\) has the same length as the vector \(\mathbf{\vec a} - \mathbf{\vec b}\), but goes in the opposite direction.</p>

<figure>
   <img src="/images/math-image178.png" />
   <figcaption>Figure (10): Vector subtraction.</figcaption>
</figure>

<p>In general, if we have two vectors, \(\mathbf{\vec a}\) and \(\mathbf{\vec b}\), then \(\mathbf{\vec a} - \mathbf{\vec b}\) is a vector that is calculated as follows:</p>

<p>\(\mathbf{\vec a} = &lt;a_1, a_2, a_3&gt;\)<br />
\(\mathbf{\vec b} = &lt;b_1, b_2, b_3&gt;\)<br />
\(\mathbf{\vec a}-\mathbf{\vec b} = &lt;a_1 - b_1, a_2 - b_2, a_3 - b_3&gt; = \mathbf{\mathbf{\vec b}a}\)</p>

<p>Vector subtraction is commonly used to find vectors between points. So if we need to find a vector that goes from the tip point of the position vector \(\mathbf{\vec b}\) to the tip point of the position vector \(\mathbf{\vec a}\), then we use vector subtraction \((\mathbf{\vec a}-\mathbf{\vec b})\) as shown in Figure (11).</p>

<figure>
   <img src="/images/math-image180.png" />
   <figcaption>Figure (11): Use vector subtraction to find a vector between two points. </figcaption>
</figure>

<div class="embed-responsive embed-responsive-16by9 video-player">
  <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/RQK8pCIWKNY?showinfo=0&amp;rel=0&amp;modestbranding=1" frameborder="0" allow="accelerometer; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe>
</div>

<p><br /></p>

<h3 id="vector-properties">Vector properties</h3>

<p>There are eight properties of vectors. If a, b, and c are vectors, and s and t are numbers, then:</p>

<p>\(\mathbf{\vec a} + \mathbf{\vec b} = \mathbf{\vec b} + \mathbf{\vec a}\)<br />
\(\mathbf{\vec a} + 0 = a\)<br />
\(s * (\mathbf{\vec a} + \mathbf{\vec b}) = s * a + s * \mathbf{\vec b}\)<br />
\(s * t * (\mathbf{\vec a}) = s * (t * \mathbf{\vec a})\)<br />
\(\mathbf{\vec a} + (\mathbf{\vec b} + \mathbf{\vec c}) = (\mathbf{\vec a} + \mathbf{\vec b}) + \mathbf{\vec c}\)<br />
\(\mathbf{\vec a} + (-\mathbf{\vec a}) = 0\)<br />
\((s + t) * \mathbf{\vec a} = s * \mathbf{\vec a} + t * \mathbf{\vec a}\)<br />
\(1 * \mathbf{\vec a} = \mathbf{\vec a}\)</p>

<h3 id="vector-dot-product">Vector dot product</h3>

<p>The dot product takes two vectors and produces a number.
For example, if we have the two vectors a and b so that:</p>

<p>\(\mathbf{\vec a} = &lt;1, 2, 3&gt;\)<br />
\(\mathbf{\vec b} = &lt;5, 6, 7&gt;\)</p>

<p>Then the dot product is the sum of multiplying the components as follows:</p>

<p>\(\mathbf{\vec a} · \mathbf{\vec b} = 1 * 5 + 2 * 6 + 3 * 7\)<br />
\(\mathbf{\vec a} · \mathbf{\vec b} = 38\)</p>

<p>In general, given the two vectors a and b:</p>

<p>\(\mathbf{\vec a} = &lt;a_1, a_2, a_3&gt;\)<br />
\(\mathbf{\vec b} = &lt;b_1, b_2, b_3&gt;\)<br />
\(\mathbf{\vec a} · \mathbf{\vec b} = a_1 * b_1 + a_2 * b_2 + a_3 * b_3\)</p>

<p>We always get a positive number for the dot product between two vectors when they go in the same general direction. A negative dot product between two vectors means that the two vectors go in the opposite general direction.</p>

<figure>
   <img src="/images/math-image181.png" />
   <figcaption>Figure (12): When the two vectors go in the same direction (left), the result is a positive dot product. When the two vectors go in the opposite direction (right), the result is a negative dot product. </figcaption>
</figure>

<p>When calculating the dot product of two unit vectors, the result is always between 1 and +1. For example:</p>

<p>\(\mathbf{\vec a} = &lt;1, 0, 0&gt;\)<br />
\(\mathbf{\vec b} = &lt;0.6, 0.8, 0&gt;\)<br />
\(\mathbf{\vec a} · \mathbf{\vec b} = (1 * 0.6, 0 * 0.8, 0 * 0) = 0.6\)</p>

<p>In addition, the dot product of a vector with itself is equal to that vector’s length to the power of two. For example:</p>

<p>\(\mathbf{\vec a} = &lt;0, 3, 4&gt;\)<br />
\(\mathbf{\vec a} · \mathbf{\vec a} = 0 * 0 + 3 * 3 + 4 * 4\)<br />
\(\mathbf{\vec a} · \mathbf{\vec a} = 25\)</p>

<p>Calculating the square length of vector \(\mathbf{\vec a}\) :</p>

<p>\(\vert \mathbf{\vec a} \vert = \sqrt{4^2 + 3^2 + 0^2}\)<br />
\(\vert \mathbf{\vec a} \vert = 5\)<br />
\(\vert \mathbf{\vec a} \vert 2 = 25\)</p>

<h3 id="vector-dot-product-lengths-and-angles">Vector dot product, lengths, and angles</h3>

<p>There is a relationship between the dot product of two vectors and the angle between them.</p>

<div class="note">
  <p>The dot product of two non-zero unit vectors equals the cosine of the angle between them.</p>
</div>

<p>In general:</p>

<p>\(\mathbf{\vec a} · \mathbf{\vec b} = \vert \mathbf{\vec a} \vert * \vert \mathbf{\vec b} \vert * cos(ө)\) , or<br />
\(\mathbf{\vec a} · \mathbf{\vec b} / (\vert \mathbf{\vec a} \vert * \vert \mathbf{\vec b} \vert) = cos(ө)\)</p>

<p>Where:</p>

<p>\(ө\) is the angle included between the vectors.</p>

<p>If vectors a and b are unit vectors, we can simply say:</p>

<p>\(\mathbf{\vec a} · \mathbf{\vec b} = cos(ө)\)</p>

<p>And since the cosine of a 90-degree angle is equal to 0, we can say:</p>

<div class="note">
  <p>Vectors \(\vec a\) and \(\vec b\) are orthogonal if, and only if, \(\vec{a} \cdot  \vec{b} = 0\).</p>
</div>

<p>For example, if we calculate the dot product of the two orthogonal vectors, World xaxis and yaxis, the result will equal zero.</p>

<p>\(\mathbf{\vec x} = &lt;1, 0, 0&gt;\)<br />
\(\mathbf{\vec y} = &lt;0, 1, 0&gt;\)<br />
\(\mathbf{\vec x} · \mathbf{\vec y} = (1 * 0) + (0 * 1) + (0 * 0)\)<br />
\(\mathbf{\vec x} · \mathbf{\vec y} = 0\)</p>

<p>There is also a relationship between the dot product and the projection length of one vector onto another. For example:</p>

<p>\(\mathbf{\vec a} = &lt;5, 2, 0&gt;\)<br />
\(\mathbf{\vec b} = &lt;9, 0, 0&gt;\)<br />
\(unit(\mathbf{\vec b}) = &lt;1, 0, 0&gt;\)<br />
\(\mathbf{\vec a} · unit(\mathbf{\vec b}) = (5 * 1) + (2 * 0) + (0 * 0)\)<br />
\(\mathbf{\vec a} · unit(\mathbf{\vec b}) = 2 (\text{which is equal to the projection length of mathbf{\vec a} onto mathbf{\vec b}})\)</p>

<figure>
   <img src="/images/math-image182.png" />
   <figcaption>Figure (13): The dot product equals the projection length of one vector onto a non-zero unit vector. </figcaption>
</figure>

<p>In general, given a vector a and a non-zero vector b, we can calculate the projection length pL of vector a onto vector b using the dot product.</p>

<p>\(pL = \vert \mathbf{\vec a} \vert * cos(ө)\)<br />
\(pL = \mathbf{\vec a} · unit(\mathbf{\vec b})\)</p>

<div class="embed-responsive embed-responsive-16by9 video-player">
  <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/ZsM2RQbVDf4?showinfo=0&amp;rel=0&amp;modestbranding=1" frameborder="0" allow="accelerometer; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe>
</div>

<p><br /></p>

<h3 id="dot-product-properties">Dot product properties</h3>

<p>If \(\mathbf{\vec a}\), \(\mathbf{\vec b}\), and \(\mathbf{\vec c}\) are vectors and s is a number, then:</p>

<p>\(\mathbf{\vec a} · \mathbf{\vec a} = \vert  \mathbf{\vec a} \vert ^2\)<br />
\(\mathbf{\vec a} · (\mathbf{\vec b} + \mathbf{\vec c}) = \mathbf{\vec a} · \mathbf{\vec b} + \mathbf{\vec a} · \mathbf{\vec c}\)<br />
\(0 · \mathbf{\vec a} = 0\)<br />
\(\mathbf{\vec a} · \mathbf{\vec b} = \mathbf{\vec b} · \mathbf{\vec a}\)<br />
\((s * \mathbf{\vec a}) · \mathbf{\vec b} = s * (\mathbf{\vec a} · \mathbf{\vec b}) = \mathbf{\vec a} · (s * \mathbf{\vec b})\)</p>

<h3 id="vector-cross-product">Vector cross product</h3>

<p>The cross product takes two vectors and produces a third vector that is orthogonal to both.</p>

<figure>
   <img src="/images/math-image183.png" />
   <figcaption>Figure (14): Calculating the cross product of two vectors. </figcaption>
</figure>

<p>For example, if you have two vectors lying on the World xy-plane, then their cross product is a vector perpendicular to the xy-plane going either in the positive or negative World z-axis direction. For example:</p>

<p>\(\mathbf{\vec a} = &lt;3, 1, 0&gt;\)<br />
\(\mathbf{\vec b} = &lt;1, 2, 0&gt;\)<br />
\(\mathbf{\vec a} × \mathbf{\vec b} = &lt; (1 * 0 – 0 * 2), (0 * 1 - 3 * 0), (3 * 2 - 1 * 1) &gt;\)<br />
\(\mathbf{\vec a} × \mathbf{\vec b} = &lt;0, 0, 5&gt;\)</p>

<div class="note">
  <p>The vector \(\vec a \times \vec b\) is orthogonal to both \(\vec a\) and \(\vec b\).</p>
</div>

<p>You will probably never need to calculate a cross product of two vectors by hand, but if you are curious about how it is done, continue reading; otherwise you can safely skip this section. The cross product \(a × b\) is defined using determinants. Here is a simple illustration of how to calculate a determinant using the standard basis vectors:</p>

<p>\(\color {red}{i} = &lt;1, 0, 0&gt;\)<br />
\(\color {blue}{j} = &lt;0,1, 0&gt;\)<br />
\(\color {green}{k} = &lt;0, 0, 1&gt;\)</p>

<p><img src="/images/math-image184.png" /></p>

<p>The cross product of the two vectors \(\mathbf{\vec a} = &lt;a1, a2, a3&gt;\) and \(\mathbf{\vec b} = &lt;b1, b2, b3&gt;\) is calculated as follows using the above diagram:</p>

<p>\(\mathbf{\vec a} × \mathbf{\vec b} = \color {red}{i (a_2 * b_3)} + \color {blue}{ j (a_3 * b_1)} + \color {green}{k(a_1 * b_2)} - \color {green}{k (a_2 * b_1)} - \color {red}{i (a_3 * b_2)} -\color {blue}{ j (a_1 * b_3)}\)<br />
\(\mathbf{\vec a} × \mathbf{\vec b} = \color {red}{i (a_2 * b_3 - a_3 * b_2)} + \color {blue}{j (a_3 * b_1 - a_1 * b_3)} +\color {green}{k (a_1 * b_2 - a_2 * b_1)}\)<br />
\(\mathbf{\vec a} × \mathbf{\vec b} = &lt;\color {red}{a_2 * b_3 – a_3 * b_2},  \color {blue}{a_3 * b_1 - a_1 * b_3},  \color {green}{a_1 * b_2 - a_2 * b_1} &gt;\)</p>

<div class="embed-responsive embed-responsive-16by9 video-player">
  <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/I5WkhSo4p6o?showinfo=0&amp;rel=0&amp;modestbranding=1" frameborder="0" allow="accelerometer; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe>
</div>

<p><br /></p>

<h3 id="cross-product-and-angle-between-vectors">Cross product and angle between vectors</h3>

<p>There is a relationship between the angle between two vectors and the length of their cross product vector. The smaller the angle (smaller sine); the shorter the cross product vector will be. The order of operands is important in vectors cross product. For example:</p>

<p>\(\mathbf{\vec a} = &lt;1, 0, 0&gt;\)<br />
\(\mathbf{\vec b} = &lt;0, 1, 0&gt;\)<br />
\(\mathbf{\vec a} × \mathbf{\vec b} = &lt;0, 0, 1&gt;\)<br />
\(\mathbf{\vec b} × \mathbf{\vec a} = &lt;0, 0, -1&gt;\)</p>

<figure>
   <img src="/images/math-image185.png" />
   <figcaption>Figure (15): The relationship between the sine of the angle between two vectors and the length of their cross product vector.</figcaption>
</figure>

<p>In Rhino’s right-handed system, the direction of \(\mathbf{\vec a} × \mathbf{\vec b}\) is given by the right-hand rule (where \(\mathbf{\vec a}\) = index finger, \(\mathbf{\vec b}\) = middle finger, and \(\mathbf{\vec a} × \mathbf{\vec b}\) = thumb).</p>

<p><img src="/images/math-image186.png" width="375px" /></p>

<p>In general, for any pair of 3-D vectors \(\mathbf{\vec a}\) and \(\mathbf{\vec b}\):</p>

<p>\(\vert \mathbf{\vec a} × \mathbf{\vec b} \vert  = \vert  \mathbf{\vec a} \vert  \vert  \mathbf{\vec b} \vert  sin(ө)\)</p>

<p>Where:</p>

<p>\(ө\) is the angle included between the position vectors of \(\mathbf{\vec a}\) and \(\mathbf{\vec b}\)</p>

<p>If a and b are unit vectors, then we can simply say that the length of their cross product equals the sine of the angle between them. In other words:</p>

<p>\(\vert \mathbf{\vec a} × \mathbf{\vec b} \vert = sin(ө)\)</p>

<p>The cross product between two vectors helps us determine if two vectors are parallel. This is because the result is always a zero vector.</p>

<div class="note">
  <p>Vectors \(\vec a\) and \(\vec b\) are parallel if, and only if, \(a \times b = 0\).</p>
</div>

<h3 id="cross-product-properties">Cross product properties</h3>

<p>If \(\mathbf{\vec a}\), \(\mathbf{\vec b}\), and \(\mathbf{\vec c}\) are vectors, and \(s\) is a number, then:<br />
\(\mathbf{\vec a} × \mathbf{\vec b} = -\mathbf{\vec b} × \mathbf{\vec a}\) <br />
\((s * \mathbf{\vec a}) × \mathbf{\vec b} = s * (\mathbf{\vec a} × \mathbf{\vec b}) = \mathbf{\vec a} × (s * \mathbf{\vec b})\)<br />
\(\mathbf{\vec a} × (\mathbf{\vec b} + \mathbf{\vec c}) = \mathbf{\vec a} × \mathbf{\vec b} + \mathbf{\vec a} × \mathbf{\vec c}\)<br />
\((\mathbf{\vec a} + \mathbf{\vec b}) × \mathbf{\vec c} = \mathbf{\vec a} × \mathbf{\vec c} + \mathbf{\vec b} × \mathbf{\vec c}\)<br />
\(\mathbf{\vec a} · (\mathbf{\vec b} × \mathbf{\vec c}) = (\mathbf{\vec a} × \mathbf{\vec b}) · \mathbf{\vec c}\)<br />
\(\mathbf{\vec a} × (\mathbf{\vec b} × \mathbf{\vec c}) = (\mathbf{\vec a} · \mathbf{\vec c}) * \mathbf{\vec b} – (\mathbf{\vec a} · \mathbf{\vec b}) * \mathbf{\vec c}\)</p>

<h2 id="13-vector-equation-of-line">1.3 Vector equation of line</h2>

<p>The vector line equation is used in 3D modeling applications and computer graphics.</p>

<figure>
   <img src="/images/math-image187.png" />
   <figcaption>Figure (16): Vector equation of a line.</figcaption>
</figure>

<p>For example, if we know the direction of a line and a point on that line, then we can find any other point on the line using vectors, as in the following:</p>

<p>\(\overline{L} = line\)<br />
\(\mathbf{\vec v} = &lt;a, b, c&gt;\) line direction unit vector<br />
\(Q = (x_0, y_0, z_0)\) line position point<br />
\(P = (x, y, z)\) any point on the line</p>

<p>We know that:</p>

<p>\(\mathbf{\vec a} = t *\mathbf{\vec v}\)   (2)<br />
\(\mathbf{\vec p} = \mathbf{\vec q} + \mathbf{\vec a}\)   (1)</p>

<p>From 1 and 2:</p>

<p>\(\mathbf{\vec p} = \mathbf{\vec q} + t * \mathbf{\vec v}\)  (3)</p>

<p>However, we can write (3) as follows:</p>

<p>\(&lt;x, y, z&gt; = &lt;x_0, y_0, z_0&gt; + &lt;t * a, t * b, t * c&gt;\)<br />
\(&lt;x, y, z&gt; = &lt;x_0 + t * a, y_0 + t * b, z_0 + t * c&gt;\)</p>

<p>Therefore:</p>

<p>\(x = x_0 + t * a\)<br />
\(y = y_0 + t * b\)<br />
\(z = z_0 + t * c\)</p>

<p>Which is the same as:</p>

<p>\(P = Q + t * \mathbf{\vec v}\)</p>

<div class="note">
  <p>Given a point \(Q\) and a direction \(\vec v\) on a line, any point \(P\) on that line can be calculated using the vector equation of a line \(P = Q + t * \vec v\) where \(t\) is a number.</p>
</div>

<p>Another common example is to find the midpoint between two points. The following shows how to find the midpoint using the vector equation of a line:</p>

<p>\(\mathbf{\vec q}\) is the position vector for point \(Q\)<br />
\(\mathbf{\vec p}\) is the position vector for point \(P\)<br />
\(\mathbf{\vec a}\) is the vector going from \(Q \rightarrow P\)</p>

<p>From vector subtraction, we know that:</p>

<p>\(\mathbf{\vec a} = \mathbf{\vec p} - \mathbf{\vec q}\)</p>

<p>From the line equation, we know that:</p>

<p>\(M = Q + t * \mathbf{\vec a}\)</p>

<p>And since we need to find midpoint, then:</p>

<p>\(t = 0.5\)</p>

<p>Hence we can say:</p>

<p>\(M = Q + 0.5 * \mathbf{\vec a}\)</p>

<figure>
   <img src="/images/math-image159.png" />
   <figcaption>Figure (17): Find the midpoint between two input points.</figcaption>
</figure>

<p>In general, you can find any point between \(Q\) and \(P\) by changing the \(t\) value between 0 and 1 using the general equation:</p>

<p>\(M = Q + t * (P - Q)\)</p>

<div class="note">
  <p>Given two points \(Q\) and \(P\), any point \(M\) between the two points is calculated using the equation \(M = Q + t * (P - Q)\) where t is a number between 0 and 1.</p>
</div>

<h2 id="14-vector-equation-of-a-plane">1.4 Vector equation of a plane</h2>

<p>One way to define a plane is when you have a point and a vector that is perpendicular to the plane. That vector is usually referred to as normal to the plane. The normal points in the direction above the plane.</p>

<p>One example of how to calculate a plane normal is when we know three non-linear points on the plane.</p>

<p>In Figure (16), given:</p>

<p>\(A\) = the first point on the plane<br />
\(B\) = the second point on the plane<br />
\(C\) = the third point on the plane</p>

<p>And:</p>

<p>\(\mathbf{\vec a}\) = a position vector of point \(A\)<br />
\(\mathbf{\vec b}\) = a position vector of point \(B\)<br />
\(\mathbf{\vec c}\) = a position vector of point \(C\)</p>

<p>We can find the normal vector \(\mathbf{\vec n}\) as follows:</p>

<p>\(\mathbf{\vec n} = (\mathbf{\vec b} - \mathbf{\vec a}) × (\mathbf{\vec c} - \mathbf{\vec a})\)</p>

<figure>
   <img src="/images/math-image160.png" />
   <figcaption>Figure (18): Vectors and planes</figcaption>
</figure>

<p>We can also derive the scalar equation of the plane using the vector dot product:</p>

<p>\(\mathbf{\vec n} · (\mathbf{\vec b} - \mathbf{\vec a}) = 0\)</p>

<p>If:</p>

<p>\(\mathbf{\vec n} = &lt;a, b, c&gt;\)<br />
\(\mathbf{\vec b} = &lt;x, y, z&gt;\)<br />
\(\mathbf{\vec a} = &lt;x_0, y_0, z_0&gt;\)</p>

<p>Then we can expand the above:</p>

<p>\(&lt;a, b, c&gt; · &lt;x-x_0, y-y_0, z-z_0 &gt; = 0\)</p>

<p>Solving the dot product gives the general scalar equation of a plane:</p>

<p>\(a * (x - x_0) + b * (y - y_0) + c * (z - z_0) = 0\)</p>

<h2 id="15-tutorials">1.5 Tutorials</h2>

<p>All the concepts we reviewed in this chapter have a direct application to solving common geometry problems encountered when modeling. The following are stepbystep tutorials that use the concepts learned in this chapter using Rhinoceros and Grasshopper (GH).</p>

<h3 id="151-face-direction">1.5.1 Face direction</h3>
<p>Given a point and a surface, how can we determine whether the point is facing the front or back side of that surface?</p>

<p><strong>Input:</strong></p>

<ol>
  <li>a surface</li>
  <li>a point</li>
</ol>

<p><img src="/images/math-image161.png" /></p>

<p><strong>Parameters:</strong></p>

<p>The face direction is defined by the surface normal direction. We will need the following information:</p>

<ul>
  <li>The surface normal direction at a surface location closest to the input point.</li>
  <li>A vector direction from the closest point to the input point.</li>
</ul>

<p>Compare the above two directions, if going the same direction, the point is facing the front side, otherwise it is facing the back.</p>

<p><strong>Solution:</strong></p>

<p>1. Find the closest point location on the surface relative to the input point using the Pull component. This will give us the uv location of the closest point, which we can then use to evaluate the surface and find its normal direction.</p>

<p><img src="/images/math-image162.png" /></p>

<p>2. We can now use the closest point to draw a vector going towards the input point. We can also draw:</p>

<p><img src="/images/math-image163.png" /></p>

<p>3. We can compare the two vectors using the dot product. If the result is positive, the point is in front of the surface. If the result is negative, the point is behind the surface.</p>

<p><img src="/images/math-image164.png" /></p>

<p>The above steps can also be solved using other scripting languages. Using the Grasshopper VB component:</p>

<p><img src="/images/math-image165.png" /></p>

<pre><code class="language-vb">Private Sub RunScript(ByVal pt As Point3d, ByVal srf As Surface, ByRef A As Object)

  'Declare variables
  Dim u, v As Double
  Dim closest_pt As Point3d

  'get closest point u, v
  srf.ClosestPoint(pt, u, v)

  'get closest point
  closest_pt = srf.PointAt(u, v)

  'calculate direction from closest point to test point
  Dim dir As New Vector3d(pt - closest_pt)

  'calculate surface normal
  Dim normal = srf.NormalAt(u, v)

  'compare the two directions using the dot product
  A = dir * normal
End Sub
</code></pre>

<p>Using the Grasshopper Python component with RhinoScriptSyntax:</p>

<p><img src="/images/math-image14.png" /></p>

<pre><code class="language-python">import rhinoscriptsyntax as rs #import RhinoScript library

#find the closest point
u, v = rs.SurfaceClosestPoint(srf, pt)

#get closest point
closest_pt = rs.EvaluateSurface(srf, u, v)

#calculate direction from closest point to test point
dir = rs.PointCoordinates(pt) - closest_pt

#calculate surface normal
normal = rs.SurfaceNormal(srf, [u, v])

#compare the two directions using the dot product
A = dir * normal
</code></pre>

<p>Using the Grasshopper Python component with RhinoCommon only:</p>

<p><img src="/images/math-image13.png" /></p>

<pre><code class="language-python">#find the closest point
found, u, v = srf.ClosestPoint(pt)

if found:

    #get closest point
    closest_pt = srf.PointAt(u, v)

    #calculate direction from closest point to test point
    dir = pt - closest_pt

    #calculate surface normal
    normal = srf.NormalAt(u, v)

    #compare the two directions using the dot product
    A = dir * normal
</code></pre>

<p>Using the Grasshopper C# component:</p>

<p><img src="/images/math-image165.png" /></p>

<pre><code class="language-cs">private void RunScript(Point3d pt, Surface srf, ref object A)
{
  //Declare variables
  double u, v;
  Point3d closest_pt;

  //get closest point u, v
  srf.ClosestPoint(pt, out u, out v);

  //get closest point
  closest_pt = srf.PointAt(u, v);

  //calculate direction from closest point to test point
  Vector3d dir = pt - closest_pt;

  //calculate surface normal
  Vector3d normal = srf.NormalAt(u, v);

  //compare the two directions using the dot product
  A = dir * normal;
}
</code></pre>

<h3 id="152-exploded-box">1.5.2 Exploded box</h3>

<p>The following tutorial shows how to explode a polysurface. This is what the final exploded box looks like:</p>

<p><img src="/images/math-image15.jpg" /></p>

<p><strong>Input:</strong></p>

<p>Identify the input, which is a box. We will use the Box parameter in GH:</p>

<p><img src="/images/math-image17.jpg" /></p>

<p><strong>Parameters:</strong></p>

<ul>
  <li>Think of all the parameters we need to know in order to solve this tutorial.</li>
  <li>The center of explosion.</li>
  <li>The box faces we are exploding.</li>
  <li>The direction in which each face is moving.</li>
</ul>

<p><img src="/images/math-image19.jpg" /></p>

<p>Once we have identified the parameters, it is a matter of putting it together in a solution by piecing together the logical steps to reach an answer.</p>

<p><strong>Solution:</strong></p>

<p>1. Find the center of the box using the <strong>Box Properties</strong> component in GH:</p>

<p><img src="/images/math-image21.png" /></p>

<p>2. Extract the box faces with the <strong>Deconstruct Brep</strong> component:</p>

<p><img src="/images/math-image23.png" /></p>

<p>3. The direction we move the faces is the tricky part. We need to first find the center of each face, and then define the direction from the center of the box towards the center of each face as follows:</p>

<p><img src="/images/math-image25.png" /></p>

<p>4. Once we have all the parameters scripted, we can use the <strong>Move</strong> component to move the faces in the appropriate direction. Just make sure to set the vectors to the desired amplitude, and you will be good to go.</p>

<p><img src="/images/math-image27.png" /></p>

<p>The above steps can also be solved using VB script, C# or Python. Following is the solution using these scripting languages.</p>

<p>Using the Grasshopper VB component:</p>

<p><img src="/images/math-image29.png" /></p>

<pre><code class="language-vb">Private Sub RunScript(ByVal box As Brep, ByVal dis As Double, ByRef A As Object)

    'get the brep center
    Dim area As Rhino.Geometry.AreaMassProperties
    area = Rhino.Geometry.AreaMassProperties.Compute(box)

    Dim box_center As Point3d
    box_center = area.Centroid

    'get a list of faces
    Dim faces As Rhino.Geometry.Collections.BrepFaceList = box.Faces

    'decalre variables
    Dim center As Point3d
    Dim dir As Vector3d
    Dim exploded_faces As New List( Of Rhino.Geometry.Brep )
    Dim i As Int32
    'loop through all faces

    For i = 0 To faces.Count() - 1
      'extract each of the face
      Dim extracted_face As Rhino.Geometry.Brep = box.Faces.ExtractFace(i)

      'get the center of each face
      area = Rhino.Geometry.AreaMassProperties.Compute(extracted_face)
      center = area.Centroid

      'calculate move direction (from box centroid to face center)
      dir = center - box_center
      dir.Unitize()
      dir *= dis

      'move the extracted face
      extracted_face.Transform(Transform.Translation(dir))

      'add to exploded_faces list
      exploded_faces.Add(extracted_face)
    Next

    'assign exploded list of faces to output
    A = exploded_faces
  End Sub
</code></pre>
<p>Using the Grasshopper Python component with RhinoCommon:</p>

<p><img src="/images/math-image4.png" /></p>

<pre><code class="language-python">import Rhino #import RhinoCommon module

#find a point between A and B
D = A + t * (B - A)

#find mid point between A and D
C1 = A + 0.5 * (D - A)

#find mid point between D and B
C2 = D + 0.5 * (B - D)

#find spheres radius
r1 = A.DistanceTo(C1)
r2 = B.DistanceTo(C2)

#create spheres and assign to output
S1 = Rhino.Geometry.Sphere(C1, r1)
S2 = Rhino.Geometry.Sphere(C2, r2)
</code></pre>

<p>Using the Grasshopper C# component:</p>

<p><img src="/images/math-image2.png" /></p>

<pre><code class="language-cs">private void RunScript(Brep box, double dis, ref object A)
{

    //get the brep center
  Rhino.Geometry.AreaMassProperties area =        Rhino.Geometry.AreaMassProperties.Compute(box);
  Point3d box_center = area.Centroid;

  //get a list of faces
  Rhino.Geometry.Collections.BrepFaceList faces = box.Faces;

  //decalre variables
  Point3d center;   Vector3d dir;
  List&lt;Rhino.Geometry.Brep&gt; exploded_faces = new List&lt;Rhino.Geometry.Brep&gt;();

  //loop through all faces   for( int i = 0; i &lt; faces.Count(); i++ )
  {
    //extract each of the face
    Rhino.Geometry.Brep extracted_face = box.Faces.ExtractFace(i);

    //get the center of each face
    area = Rhino.Geometry.AreaMassProperties.Compute(extracted_face);
    center = area.Centroid;

    //calculate move direction (from box centroid to face center)
    dir = center - box_center;
    dir.Unitize();
    dir *= dis;

    //move the extracted face
    extracted_face.Transform(Transform.Translation(dir));

    //add to exploded_faces list
    exploded_faces.Add(extracted_face);
  }

  //assign exploded list of faces to output
  A = exploded_faces;
}
</code></pre>

<h3 id="153-tangent-spheres">1.5.3 Tangent spheres</h3>

<p>This tutorial will show how to create two tangent spheres between two input points.
This is what the result looks like:</p>

<p><img src="/images/math-image5.png" /></p>

<p><strong>Input:</strong><br />
Two points (\(A\) and \(B\)) in the 3-D coordinate system.</p>

<p><img src="/images/math-image6.png" /></p>

<p>Parameters:
The following is a diagram of the parameters that we will need in order to solve the problem:
\(A\) tangent point \(D\) between the two spheres, at some \(t\) parameter (0-1) between points \(A\) and \(B\).</p>

<ul>
  <li>The center of the first sphere or the midpoint \(C1\) between \(A\) and \(D\).</li>
  <li>The center of the second sphere or the midpoint \(C2\) between \(D\) and \(B\).</li>
  <li>The radius of the first sphere \((r1)\) or the distance between \(A\) and \(C1\).</li>
  <li>The radius of the second sphere \((r2)\) or the distance between \(D\) and \(C2\).</li>
</ul>

<p><strong>Solution:</strong></p>

<p>1. Use the <strong>Expression</strong> component to definepoint \(D\) between \(A\) and \(B\) atsome parameter \(t\). The expression we will use is based onthe vector equation of a line:</p>

<p>\(D = A + t*(B-A)\)</p>

<p>$$B-A\(: is the vector that goes from\)B\(to\)A  (\vec{BA}) using the vector subtraction   operation.</p>

<p>$$t*(B-A)\(: where\)t$$ is between 0 and 1 to get us a location on the vector.</p>

<p>$$A+t*(B-A)$$ : gets apoint on the vector between A and B.</p>

<p><img src="/images/math-image8.png" /></p>

<p>2. Use the Expression component to also define the mid points \(C1\) and \(C2\).</p>

<p><img src="/images/math-image9.png" /></p>

<p>3. The first sphere radius \((r1)\) and the second sphere radius \((r2)\) can be calculated using the <strong>Distance</strong> component.</p>

<p><img src="/images/math-image10.png" /></p>

<p>4. The final step involves creating the sphere from a base plane and radius. We need to make sure the origins are hooked to \(C1\) and \(C2\) and the radius from \(r1\) and \(r2\).</p>

<p><img src="/images/math-image54.png" /></p>

<p><strong>Using the Grasshopper VB component:</strong></p>

<p><img src="/images/math-image56.png" /></p>

<pre><code class="language-vb">Private Sub RunScript(ByVal A As Point3d, ByVal B As Point3d, ByVal t As Double, ByRef S1 As Object, ByRef S2 As Object)

  'declare variables
  Dim D, C1, C2 As Rhino.Geometry.Point3d
  Dim r1, r2 As Double

  'find a point between A and B
  D = A + t * (B - A)

  'find mid point between A and D
  C1 = A + 0.5 * (D - A)

  'find mid point between D and B
  C2 = D + 0.5 * (B - D)
  'find spheres radius
  r1 = A.DistanceTo(C1)
  r2 = B.DistanceTo(C2)

  'create spheres and assign to output
  S1 = New Rhino.Geometry.Sphere(C1, r1)
  S2 = New Rhino.Geometry.Sphere(C2, r2)

End Sub
</code></pre>

<p>Using Python component:</p>

<p><img src="/images/math-image62.png" /></p>

<pre><code class="language-python">import Rhino

#find a point between A and B
D = A + t * (B - A)

#find mid point between A and D
C1 = A + 0.5 * (D - A)

#find mid point between D and B
C2 = D + 0.5 * (B - D)

#find spheres radius
r1 = A.DistanceTo(C1)
r2 = B.DistanceTo(C2)

#create spheres and assign to output
S1 = Rhino.Geometry.Sphere(C1, r1)
S2 = Rhino.Geometry.Sphere(C2, r2)
</code></pre>

<p>Using the Grasshopper C# component:</p>

<p><img src="/images/math-image58.png" /></p>

<pre><code class="language-cs">private void RunScript(Point3d A, Point3d B, double t, ref object S1, ref object S2)
{
  //declare variables
  Rhino.Geometry.Point3d D, C1, C2;
  double r1, r2;

  //find a point between A and B
  D = A + t * (B - A);

  //find mid point between A and D
  C1 = A + 0.5 * (D - A);

  //find mid point between D and B
  C2 = D + 0.5 * (B - D);

  //find spheres radius
  r1 = A.DistanceTo(C1);
  r2 = B.DistanceTo(C2);

  //create spheres and assign to output
  S1 = new Rhino.Geometry.Sphere(C1, r1);
  S2 = new Rhino.Geometry.Sphere(C2, r2);
}
</code></pre>

<hr />

<h2 id="download-sample-files">Download Sample Files</h2>

<p>Download the <a href="/files/math-samplesandtutorials.zip.zip"><span class="glyphicon glyphicon-download"></span></a> <a href="/files/math-samplesandtutorials.zip">math-samplesandtutorials.zip</a> archive, containing all the example Grasshopper and code files in this guide.</p>

<hr />

<h2 id="next-steps">Next Steps</h2>

<p>Now that you know vector math, check out the <a href="/guides/general/essential-mathematics/matrices-transformations/">Matrices and Transformations</a> guide to learn more about the moving, rotating and scaling objects..</p>

        </article>

      <!--</div>-->

    </div>
</div>
</div>

        <!--/div-->
      </div>

      <footer class="site-footer">

  <div class="wrapper">

    <div class="footer-col-wrapper">

      
        <div class="row">
          <div class="col-md-4">

            <p class="text">
              
                
                Author: <a href="/authors/rajaa_issa">Rajaa Issa</a>
              
            </p>
          </div>
          <div class="col-md-4 text-center">
            <span class="icon  icon--github">
              <svg viewBox="0 0 16 16">
                <path fill="#828282" d="M7.999,0.431c-4.285,0-7.76,3.474-7.76,7.761 c0,3.428,2.223,6.337,5.307,7.363c0.388,0.071,0.53-0.168,0.53-0.374c0-0.184-0.007-0.672-0.01-1.32 c-2.159,0.469-2.614-1.04-2.614-1.04c-0.353-0.896-0.862-1.135-0.862-1.135c-0.705-0.481,0.053-0.472,0.053-0.472 c0.779,0.055,1.189,0.8,1.189,0.8c0.692,1.186,1.816,0.843,2.258,0.645c0.071-0.502,0.271-0.843,0.493-1.037 C4.86,11.425,3.049,10.76,3.049,7.786c0-0.847,0.302-1.54,0.799-2.082C3.768,5.507,3.501,4.718,3.924,3.65 c0,0,0.652-0.209,2.134,0.796C6.677,4.273,7.34,4.187,8,4.184c0.659,0.003,1.323,0.089,1.943,0.261 c1.482-1.004,2.132-0.796,2.132-0.796c0.423,1.068,0.157,1.857,0.077,2.054c0.497,0.542,0.798,1.235,0.798,2.082 c0,2.981-1.814,3.637-3.543,3.829c0.279,0.24,0.527,0.713,0.527,1.437c0,1.037-0.01,1.874-0.01,2.129 c0,0.208,0.14,0.449,0.534,0.373c3.081-1.028,5.302-3.935,5.302-7.362C15.76,3.906,12.285,0.431,7.999,0.431z"/>
              </svg>
            </span>
            <a href="https://github.com/mcneel/developer-rhino3d-com/blob/7/_guide_topics/general/essential-mathematics/vector-mathematics.md" target="_blank">Edit page on GitHub</a>
          </div>
            <div class="col-md-4">
              <span class="pull-right">
                <span class="glyphicon glyphicon-cog"></span>&nbsp;<a href="/admin">Admin</a>
              </span>
            </div>
        </div>

        <div class="row text-center">
          © 1997 - 2022 Robert McNeel &amp; Associates<br/>
          <span class="glyphicon glyphicon-heart-empty"></span>&nbsp;<a href="/authors">Contributions welcome</a>
        </div>

      

    </div>

  </div>

  <script>
    if (navigator.appVersion.indexOf("Win")!=-1)
    {
      var body = document.getElementsByTagName("body");
      body[0].style.fontWeight = '400';
    }
  </script>

</footer>

    </div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <!-- MathJax -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>

    <script type="text/javascript">
    $('body').scrollspy({
        target: '.bs-docs-sidebar',
        offset: 150 /* fixed header is about 40px high */
    });
    </script>
  </body>
</html>
